# Generated by Django 3.2 on 2021-04-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vakcina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_firmy', models.CharField(max_length=50, verbose_name='Název firmy')),
                ('ucinnost_vakciny', models.IntegerField(verbose_name='Účinnost vakcíny v %')),
                ('cena_vakciny', models.IntegerField(null=True, verbose_name='Cena vakcíny v Kč')),
                ('typ_vakciny', models.CharField(max_length=50, verbose_name='Typ vakcíny')),
                ('pocet_davek', models.IntegerField(verbose_name='Počet dávek')),
                ('schvaleno_v_EU', models.BooleanField(verbose_name='Schváleno v EU')),
            ],
            options={
                'ordering': ['nazev_firmy'],
            },
        ),
    ]
