# Generated by Django 3.2 on 2021-04-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ockovani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Povolani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_povolani', models.CharField(max_length=50, verbose_name='Název povolání')),
            ],
            options={
                'ordering': ['nazev_povolani'],
            },
        ),
    ]
