# Generated by Django 3.2 on 2021-04-12 08:49

from django.db import migrations, models
import ockovani.models


class Migration(migrations.Migration):

    dependencies = [
        ('ockovani', '0002_povolani'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ockovani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=50, verbose_name='Příjmení')),
                ('datum_narozeni', models.DateTimeField(verbose_name='Datum narození')),
                ('datum_prvni_ockovani', models.DateTimeField(verbose_name='Datum prvního očkování')),
                ('datum_druhe_ockovani', models.DateTimeField(blank=True, null=True, verbose_name='Datum druhého očkování - dle počtu dávek vakcíny')),
                ('kod_ockovaneho', models.CharField(max_length=10, verbose_name='Kód k očkování')),
                ('kod_pojistovny', models.IntegerField(verbose_name='Kód pojišťovny')),
                ('qr', models.ImageField(blank=True, null=True, upload_to=ockovani.models.qr_path, verbose_name='QR kód')),
                ('povolani', models.ManyToManyField(to='ockovani.Povolani', verbose_name='Vyberte povolani')),
                ('vakcina', models.ManyToManyField(to='ockovani.Vakcina', verbose_name='Vyberte vakcínu')),
            ],
            options={
                'ordering': ['datum_narozeni', 'prijmeni'],
            },
        ),
    ]
